apiVersion: v1
kind: Secret
metadata:
  name: signalservice-secrets
  namespace: signalservice
type: Opaque
stringData:
  FunctionalTests__ServiceBus__ConnectionString: "Endpoint=sb://local/;SharedAccessKeyName=Root;SharedAccessKey=local"
